#!/usr/bin/env python3
"""test/load/stress: writes one baresip configuration directory (config + accounts) for a slice
of the tenant's devices, standing in for Ringotel softphones (docs/spec.md §10.4 "Branch
provision profile": `protocol: sips`, `nosrtp: false`, Opus).

Every account registers over TLS to zamfono:5061 (compose.stress.yaml maps that name, the
CN of the stack's placeholder certificate, to asterisk; the certificate itself is the CA file,
so baresip verifies the server the way a real softphone would), auto-answers, offers/accepts only Opus and
requires SDES-SRTP (`mediaenc=srtp-mand`, i.e. RTP/SAVP with a=crypto), which is what the
rendered endpoint of a `tls` device demands (packages/api/src/lib/server/pjsip/render.ts:
`media_encryption = sdes`). Audio comes from a WAV file (aufile), so each answered call encodes
real speech into Opus (complexity 0: the generator shares the host with the stack, so its own
encoder is kept cheap; Asterisk's Opus encoder settings are untouched); what the device receives
is decoded and discarded. ctrl_tcp (port
sip_port - 1080) is how devices_ctrl.py ends the calls from the device side.

Usage: gen_baresip.py <creds.csv> <out_dir> <first_index> <count> <sip_port> <wav_path>
creds.csv lines: "<sip_username>,<sip_password>" (one per device, in user order).
"""
import sys
from pathlib import Path

CONFIG = '''# generated by test/load/stress/gen_baresip.py
poll_method		epoll
sip_listen		0.0.0.0:{port}
sip_cafile		/load-gen/asterisk-ca.pem
call_local_timeout	120
call_max_calls		4
audio_player		aufile,/dev/null
audio_source		aufile,{wav}
audio_alert		aufile,/dev/null
audio_level		no
ausrc_srate		48000
auplay_srate		48000
ausrc_channels		1
auplay_channels		1
audio_buffer		20-160
rtp_tos			184
rtp_ports		40000-49999
rtp_stats		yes
jitter_buffer_delay	5-10
opus_bitrate		28000
opus_complexity		0
opus_stereo		no
opus_sprop_stereo	no
module_path		/usr/lib/baresip/modules
module			opus.so
module			srtp.so
module			aufile.so
module_app		account.so
module_app		menu.so
module_app		contact.so
module_app		ctrl_tcp.so
ctrl_tcp_listen		127.0.0.1:{ctrl}
'''


def main() -> None:
    creds_path, out_dir, first, count, port, wav = sys.argv[1:7]
    first, count = int(first), int(count)
    rows = [line.strip().split(',') for line in Path(creds_path).read_text().splitlines()
            if line.strip()]
    rows = rows[first:first + count]
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / 'config').write_text(CONFIG.format(port=port, wav=wav, ctrl=int(port) - 5080 + 4000))
    (out / 'contacts').write_text('')
    accounts = [
        f'<sip:{user}@zamfono:5061;transport=tls>;auth_pass={password};answermode=auto;'
        f'mediaenc=srtp-mand;regint=600;ptime=20'
        for user, password in rows
    ]
    (out / 'accounts').write_text('\n'.join(accounts) + '\n')
    print(f'{out}: {len(accounts)} accounts', file=sys.stderr)


if __name__ == '__main__':
    main()
