import { register } from '../registry.js';
import { clearVoicemailGreeting } from './clearVoicemailGreeting.js';
import { create } from './create.js';
import { deleteUser } from './delete.js';
import { erase } from './erase.js';
import { get } from './get.js';
import { getForwarding } from './getForwarding.js';
import { list } from './list.js';
import { resetPassword } from './resetPassword.js';
import { setForwarding } from './setForwarding.js';
import { setPresence } from './setPresence.js';
import { setVoicemailGreeting } from './setVoicemailGreeting.js';
import { update } from './update.js';

register(list);
register(get);
register(create);
register(update);
register(deleteUser);
register(resetPassword);
register(erase);
register(getForwarding);
register(setForwarding);
register(setPresence);
register(setVoicemailGreeting);
register(clearVoicemailGreeting);
