# Sourced by `run.sh`: the stack's own prerequisites (bring-up, tenant configuration, device
# registration — REUSE=1 skips all three, run.sh's own usage block) as functions, plus the two
# selectable named steps that sit either side of the scenario loop in a full run (`runtime-asserts`
# and `prompts`; `trunk-status` and `cert-sync` wrap their own files' bodies as
# `run_trunk_status_step`/`run_cert_sync_step`, called directly by run.sh).
#
# Reads and sets `run.sh`'s own COMPOSE, compose_files, repo, here, compose_cmd, API, API_PORT,
# FWD, RUNTIME, OWNER_EMAIL, OWNER_PASSWORD, MAIN_DID, FQDN and fail; sets SIP_USERNAME,
# SIP_PASSWORD and GROUP_EXT for `run-scenarios.sh` to read.

# `run.sh`'s own `.env`, then the stack itself, started fresh or, with UPGRADE_FROM, upgraded from
# a release (upgrade.sh), and `await_stack_ready`. Skipped entirely under REUSE=1.
bring_up_stack() {
  # Checked before anything binds: a pre-existing listener would answer every probe below, and
  # Docker reports the port as published either way, so the run would silently test another
  # server.
  if lsof -nP -iTCP:"$API_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    fail "something already listens on 127.0.0.1:$API_PORT; set API_PORT to a free port"
  fi

  # Stands alone, before the stack this run drives comes up: its own bring-up and tear-down of a
  # single service on a second, bridge-backed network (runtime-asserts.sh).
  assert_public_network_address

  # A throwaway tenant. The owner's password hash is generated by the api image itself, the way
  # an operator generates it (§6.3). It runs on the runtime `$COMPOSE` names, whose store holds
  # the image.
  local owner_hash
  owner_hash=$(printf '%s' "$OWNER_PASSWORD" \
    | "$RUNTIME" run --rm -i --entrypoint node "${API_IMAGE:-zamfono/api:ci}" hash-password.mjs)

  # The updater drives the runtime this run brings the stack up on (§6.3 "Updates").
  local socket=/var/run/docker.sock
  [ "$RUNTIME" != podman ] || socket=/run/podman/podman.sock

  # HEP_ENABLED is on, as a stack ships it (§7): the `*-sip-log-*` scenarios read the SIP
  # messages Asterisk mirrors to the core. EXTERNAL_IPV4 is `asterisk`'s own fixed address on
  # `internal` (compose.test.yaml), where the sipp peers send their media.
  cat > "$repo/deploy/.env" <<ENV
FQDN=$FQDN
EXTERNAL_IPV4=10.213.47.10
RTP_PORT_START=10000
RTP_PORT_END=10200
ARI_PASSWORD=ci-ari
AMI_PASSWORD=ci-ami
JWT_SECRET=$(openssl rand -base64 32)
SECRETBOX_KEY=1:$(openssl rand -base64 32)
SECRETBOX_KEY_PREVIOUS=
BACKUP_PASSWORD=$(openssl rand -hex 32)
UPDATER_TOKEN=$(openssl rand -hex 24)
CONTAINER_SOCKET=$socket
SMTP_HOST=
SMTP_PORT=
SMTP_SECURITY=
SMTP_USER=
SMTP_PASSWORD=
MAIL_FROM=
BOOTSTRAP_OWNER_EMAIL=$OWNER_EMAIL
BOOTSTRAP_OWNER_NAME=CI Owner
BOOTSTRAP_OWNER_PASSWORD_HASH='$owner_hash'
COMPANY_NAME=CI
MAIN_DID=$MAIN_DID
COUNTRY=DE
EXT_LENGTH=3
TZ=UTC
TLS_RELOAD_HOUR=3
CALL_LOG_MAX_BYTES=1048576
HEP_ENABLED=true
SIP_UDP_ENABLED=true
SIP_TCP_ENABLED=true
METRICS_TOKEN=
ENV

  if [ -n "${UPGRADE_FROM:-}" ]; then
    upgrade_from_release
  else
    echo '== bringing the stack up =='
    $COMPOSE "${compose_files[@]}" up -d
  fi
  await_stack_ready
}

# The two runtime-ordering prerequisites §6.3 names inline (migrate's exit code, the api
# healthcheck), then `core`: what a stack needs, fresh or just upgraded, before any tenant
# configuration can be driven over REST.
await_stack_ready() {
  echo '== §6.3 Runtimes: migrate ran to completion before api started =='
  local migrate_exit
  migrate_exit=$($COMPOSE "${compose_files[@]}" ps -a --format '{{.Service}} {{.ExitCode}}' \
    | awk '$1 == "migrate" { print $2 }')
  [ "$migrate_exit" = "0" ] \
    || fail "the migrate service exited $migrate_exit; service_completed_successfully did not hold"

  echo '== waiting for the api healthcheck =='
  local ready=false
  for _ in $(seq 1 60); do
    if curl -fsS "${FWD[@]}" "$API/healthz" >/dev/null 2>&1; then
      ready=true
      break
    fi
    sleep 2
  done
  [ "$ready" = true ] || fail "api never became healthy"

  echo '== waiting for core =='
  # Every configuration write asks `core` to reload Asterisk (§3.1); a write made while `core` is
  # still starting is committed with its propagation refused, so the tenant is built only once
  # `core` answers.
  local core_ready=false
  for _ in $(seq 1 60); do
    local state
    state=$($COMPOSE "${compose_files[@]}" ps --format '{{.Service}} {{.Health}}' \
      | awk '$1 == "core" { print $2 }')
    if [ "$state" = "healthy" ]; then
      core_ready=true
      break
    fi
    sleep 2
  done
  [ "$core_ready" = true ] || fail "core never became healthy"
}

# §6.3 Runtimes' own two ordering assertions (runtime-asserts.sh); selectable as `runtime-asserts`.
step_runtime_asserts() {
  assert_runtime_ordering
  assert_shared_namespace
}

# §9.1: every prompt the core plays ships in the asterisk image; selectable as `prompts`.
step_prompts() {
  bash "$here/prompts.sh" "$compose_cmd" \
    || fail "a prompt the core plays is missing from the asterisk image"
}

# The tenant §8's scenarios are played against, built over the REST API the way an operator
# builds one (`configure.sh`). Sets SIP_USERNAME, SIP_PASSWORD and GROUP_EXT for the scenario loop
# and for `save_state` (reuse.sh). Skipped entirely under REUSE=1, whose `load_state` sets the
# same three variables from what this left behind on an earlier run.
configure_tenant() {
  echo '== configuring the tenant over REST =='
  api GET /users >/dev/null || fail "GET /users did not answer for the bootstrap token"
  # Asterisk identifies a trunk by source address (§5.6), so the calling container's address
  # becomes the trunk's host and the answering container's subnet the device's allowlist.
  local trunk_ip phone_ip phone_cidr
  trunk_ip=$($COMPOSE "${compose_files[@]}" exec -T sipp hostname -i | tr -d '\r' | awk '{print $1}')
  phone_ip=$($COMPOSE "${compose_files[@]}" exec -T sipp-phone hostname -i | tr -d '\r' \
    | awk '{print $1}')
  phone_cidr="${phone_ip%.*}.0/24"
  read -r SIP_USERNAME SIP_PASSWORD GROUP_EXT < <(
    bash "$here/configure.sh" "$API" "$token" "$trunk_ip" "$phone_cidr"
  ) || fail "the tenant could not be configured over REST"
  [ -n "${SIP_USERNAME:-}" ] || fail "no device credentials came back from the configuration step"
  echo "   device $SIP_USERNAME, ring group extension $GROUP_EXT"
}

# Registers the answering device's own AOR contact, once per stack; every scenario's own call
# handling (`run-scenarios.sh`'s `start_phone_side`) reuses it. Skipped under REUSE=1: nothing
# unregisters it between runs, so a stack `KEEP=1` left up still holds it.
register_device() {
  echo '== registering the answering device =='
  bash "$here/phone.sh" "$compose_cmd" register "$SIP_USERNAME" "$SIP_PASSWORD" >/dev/null \
    || fail "the answering device never registered"
}

# §6.5 "Default target": the stack's start created a `local` target from BACKUP_PASSWORD (on the
# upgrade shard, the start of the release under test on a database the old one wrote, which had
# none), and a manual run against it creates the repository and backs up for real, through the
# image's own restic. Selectable as `backups`; cheap enough to run on every shard.
json_key() {
  python3 -c 'import json, sys; print(json.load(sys.stdin)[sys.argv[1]])' "$1"
}

step_backups() {
  echo '== backing up to the default local target =='
  local target_id run_id status='running' attempt
  target_id=$(api GET /backups/targets | python3 -c '
import json, sys
local = [t for t in json.load(sys.stdin)["items"]
         if t["kind"] == "local" and t["params"].get("path") == "/backups/restic" and t["enabled"]]
print(local[0]["id"] if len(local) == 1 else "")
') || fail "GET /backups/targets did not answer"
  [ -n "$target_id" ] || fail "the stack has no default local backup target"
  run_id=$(api POST /backups/runs "{\"targetId\":\"$target_id\"}" | json_key id) \
    || fail "POST /backups/runs refused the default target"
  # The scheduler polls for queued runs; a first run also initializes the repository.
  for attempt in $(seq 1 60); do
    status=$(api GET "/backups/runs/$run_id" | json_key status)
    [ "$status" = running ] || break
    sleep 1
  done
  [ "$status" = ok ] || fail "the backup run ended $status: $(api GET "/backups/runs/$run_id")"
  echo "   run $run_id ok after ${attempt}s"
}

# §6.3 "Updates": the updater found its own Compose project and the runtime's socket, so
# system.info carries its status rather than why it has none, and system.update reaches it with
# the token api holds: from this checkout, which pins no release, the updater refuses with 409 for
# that reason (or api does first, without a recent backup). Selectable as `updater`; after
# `backups`, on every shard, since it asks for the runtime of this run.
step_updater() {
  echo '== reaching the updater through system.info and system.update =='
  local info refusal
  info=$(api GET /system/info) || fail "GET /system/info did not answer"
  printf '%s' "$info" | python3 -c '
import json, sys
info = json.load(sys.stdin)
update = info["update"]
if "unavailable" in update or "last" not in update:
    sys.exit("the updater is not usable: %s" % json.dumps(update))
# §10.3 System, §10.4 "After a restart": core dates itself and the Asterisk it is connected to.
core = info["core"] or {}
if not core.get("startedAt") or not core.get("asteriskStartedAt"):
    sys.exit("system.info carries no core start times: %s" % json.dumps(core))
' || fail "system.info reports no usable updater, or no core start times"
  refusal=$(curl -sS -X POST "$API/api/v1/system/update" "${FWD[@]}" \
    -H "Authorization: Bearer $token" -H 'Content-Type: application/json' \
    -d '{"confirm":true}' -w '\n%{http_code}')
  case $refusal in
    *'pins no release'*$'\n'409 | *'no backup finished ok'*$'\n'409)
      echo "   refused as expected: ${refusal%$'\n'*}"
      ;;
    *) fail "system.update did not answer as expected: $refusal" ;;
  esac
}
