# Sourced by `run.sh`: the stack's own prerequisites (bring-up, tenant configuration, device
# registration — REUSE=1 skips all three, run.sh's own usage block) as functions, plus the two
# selectable named steps that sit either side of the scenario loop in a full run (`runtime-asserts`
# and `prompts`; `trunk-status` and `cert-sync` wrap their own files' bodies as
# `run_trunk_status_step`/`run_cert_sync_step`, called directly by run.sh).
#
# Reads and sets `run.sh`'s own COMPOSE, compose_files, repo, here, compose_cmd, API, API_PORT,
# FWD, RUNTIME, OWNER_EMAIL, OWNER_PASSWORD, MAIN_DID, FQDN and fail; sets SIP_USERNAME,
# SIP_PASSWORD and GROUP_EXT for `run-scenarios.sh` to read.

# `run.sh`'s own `.env`, the healthcheck wait and the two runtime-ordering prerequisites §6.3
# names inline (migrate's exit code, the api healthcheck): everything a fresh stack needs before
# any tenant configuration can be driven over REST. Skipped entirely under REUSE=1.
bring_up_stack() {
  # Checked before anything binds: a pre-existing listener would answer every probe below, and
  # Docker reports the port as published either way, so the run would silently test another
  # server.
  if lsof -nP -iTCP:"$API_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    fail "something already listens on 127.0.0.1:$API_PORT; set API_PORT to a free port"
  fi

  # Stands alone, before the stack this run drives comes up: its own bring-up and tear-down of a
  # single service on a second, bridge-backed network (runtime-asserts.sh).
  assert_public_network_address

  # A throwaway tenant. The owner's password hash is generated by the api image itself, the way
  # an operator generates it (§6.3). It runs on the runtime `$COMPOSE` names, whose store holds
  # the image.
  local owner_hash
  owner_hash=$(printf '%s' "$OWNER_PASSWORD" \
    | "$RUNTIME" run --rm -i --entrypoint node "${API_IMAGE:-zamfono/api:ci}" hash-password.mjs)

  cat > "$repo/deploy/.env" <<ENV
FQDN=$FQDN
EXTERNAL_IPV4=127.0.0.1
RTP_PORT_START=10000
RTP_PORT_END=10200
ARI_PASSWORD=ci-ari
AMI_PASSWORD=ci-ami
JWT_SECRET=$(openssl rand -base64 32)
SECRETBOX_KEY=1:$(openssl rand -base64 32)
SECRETBOX_KEY_PREVIOUS=
SMTP_HOST=
SMTP_PORT=
SMTP_SECURITY=
SMTP_USER=
SMTP_PASSWORD=
MAIL_FROM=
BOOTSTRAP_OWNER_EMAIL=$OWNER_EMAIL
BOOTSTRAP_OWNER_NAME=CI Owner
BOOTSTRAP_OWNER_PASSWORD_HASH='$owner_hash'
COMPANY_NAME=CI
MAIN_DID=$MAIN_DID
COUNTRY=DE
EXT_LENGTH=3
TZ=UTC
TLS_RELOAD_HOUR=3
CALL_LOG_MAX_BYTES=1048576
HEP_ENABLED=false
SIP_UDP_ENABLED=true
SIP_TCP_ENABLED=true
METRICS_TOKEN=
ENV

  echo '== bringing the stack up =='
  $COMPOSE "${compose_files[@]}" up -d

  echo '== §6.3 Runtimes: migrate ran to completion before api started =='
  local migrate_exit
  migrate_exit=$($COMPOSE "${compose_files[@]}" ps -a --format '{{.Service}} {{.ExitCode}}' \
    | awk '$1 == "migrate" { print $2 }')
  [ "$migrate_exit" = "0" ] \
    || fail "the migrate service exited $migrate_exit; service_completed_successfully did not hold"

  echo '== waiting for the api healthcheck =='
  local ready=false
  for _ in $(seq 1 60); do
    if curl -fsS "${FWD[@]}" "$API/healthz" >/dev/null 2>&1; then
      ready=true
      break
    fi
    sleep 2
  done
  [ "$ready" = true ] || fail "api never became healthy"

  echo '== waiting for core =='
  # Every configuration write asks `core` to reload Asterisk (§3.1); a write made while `core` is
  # still starting is committed with its propagation refused, so the tenant is built only once
  # `core` answers.
  local core_ready=false
  for _ in $(seq 1 60); do
    local state
    state=$($COMPOSE "${compose_files[@]}" ps --format '{{.Service}} {{.Health}}' \
      | awk '$1 == "core" { print $2 }')
    if [ "$state" = "healthy" ]; then
      core_ready=true
      break
    fi
    sleep 2
  done
  [ "$core_ready" = true ] || fail "core never became healthy"
}

# §6.3 Runtimes' own two ordering assertions (runtime-asserts.sh); selectable as `runtime-asserts`.
step_runtime_asserts() {
  assert_runtime_ordering
  assert_shared_namespace
}

# §9.1: every prompt the core plays ships in the asterisk image; selectable as `prompts`.
step_prompts() {
  bash "$here/prompts.sh" "$compose_cmd" \
    || fail "a prompt the core plays is missing from the asterisk image"
}

# The tenant §8's scenarios are played against, built over the REST API the way an operator
# builds one (`configure.sh`). Sets SIP_USERNAME, SIP_PASSWORD and GROUP_EXT for the scenario loop
# and for `save_state` (reuse.sh). Skipped entirely under REUSE=1, whose `load_state` sets the
# same three variables from what this left behind on an earlier run.
configure_tenant() {
  echo '== configuring the tenant over REST =='
  api GET /users >/dev/null || fail "GET /users did not answer for the bootstrap token"
  # Asterisk identifies a trunk by source address (§5.6), so the calling container's address
  # becomes the trunk's host and the answering container's subnet the device's allowlist.
  local trunk_ip phone_ip phone_cidr
  trunk_ip=$($COMPOSE "${compose_files[@]}" exec -T sipp hostname -i | tr -d '\r' | awk '{print $1}')
  phone_ip=$($COMPOSE "${compose_files[@]}" exec -T sipp-phone hostname -i | tr -d '\r' \
    | awk '{print $1}')
  phone_cidr="${phone_ip%.*}.0/24"
  read -r SIP_USERNAME SIP_PASSWORD GROUP_EXT < <(
    bash "$here/configure.sh" "$API" "$token" "$trunk_ip" "$phone_cidr"
  ) || fail "the tenant could not be configured over REST"
  [ -n "${SIP_USERNAME:-}" ] || fail "no device credentials came back from the configuration step"
  echo "   device $SIP_USERNAME, ring group extension $GROUP_EXT"
}

# Registers the answering device's own AOR contact, once per stack; every scenario's own call
# handling (`run-scenarios.sh`'s `start_phone_side`) reuses it. Skipped under REUSE=1: nothing
# unregisters it between runs, so a stack `KEEP=1` left up still holds it.
register_device() {
  echo '== registering the answering device =='
  bash "$here/phone.sh" "$compose_cmd" register "$SIP_USERNAME" "$SIP_PASSWORD" >/dev/null \
    || fail "the answering device never registered"
}
